# General Configuration
version: 1.6.1.{build}
skip_branch_with_pr: true

# Environment Configuration
image: Visual Studio 2017
cache:
  - '%LocalAppData%\NuGet\v3-cache'

install:
  #init and update submodules
  - git submodule update --recursive --init

 # version
assembly_info:
  patch: true
  file: AssemblyVersionInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'


# Build Configuration
platform: Any CPU
configuration: Release


before_build:
  - nuget restore

build:
  project: SpeckleDynamo.sln
  verbosity: minimal

after_build:
  # zip everything into a zip file containing package folder structure
  - 7z a SpeckleDynamo-%APPVEYOR_BUILD_VERSION%.zip "%APPVEYOR_BUILD_FOLDER%\SpeckleDynamo\bin\Release\Speckle for Dynamo\*"

artifacts:
  path: SpeckleDynamo-%APPVEYOR_BUILD_VERSION%.zip
  name: Release

deploy:
  - release: SpeckleDynamo-$(APPVEYOR_BUILD_VERSION)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Speckle client for Dynamo.'
    provider: GitHub
    auth_token:
      secure: D5tPFvdQMg9sIe0sSvQjEWw4KAdOk1jyxNwiH5qP5DpDmUH6n6NgTdA+56vXS1Pe # your encrypted token from GitHub
    artifact: SpeckleDynamo-$(APPVEYOR_BUILD_VERSION).zip
    draft: false
    prerelease: true
    force_update: true
    on:              # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only

notifications:
- provider: Slack
  incoming_webhook:
    secure: 9Kt/ImvGdsQ/dzmRdSaMIG+BO0R29MOJC7eZZnK5m5TyWwE+4nofEcYlb/r4lh9Z1Dx/bR+7oQtgAYO3W5s+qJshkT6Is9irYw3TfMZX7/M=
  channel: '#devtalk'
  template: Build <{{buildUrl}}|#{{buildVersion}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}}) by {{commitAuthor}} {{status}} in {{duration}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
